# STARSHIP PROMPT CONFIG

add_newline = false

[character]                           
success_symbol = "[>>>](bold green)"
error_symbol = "[>>](bold green)[>](bold red)"

[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](bold purple) "
disabled = false

[directory]
format = "in [$path]($style) [$read_only]($read_only_style)"
style = "bold cyan"
read_only = "[READ ONLY]"
read_only_style = "red"
