#! /bin/sh

# AUTOSTART
sxhkd &
setxkbmap pl
~/.config/polybar/launch.sh
#~/.fehbg
nitrogen --restore
picom -b &

# WORKSPACES
bspc monitor -d TERM WEB CHAT FILES EXTRA

# CONFIGURATION
bspc config border_width                  4
bspc config window_gap                    24
bspc config top_padding		              50
bspc config left_padding                  0
bspc config right_padding                 0
bspc config bottom_padding                0 	
bspc config single_monocle                true
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_by_distance             false
bspc config focus_follows_pointer         true
bspc config history_aware_focus           false
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# COLORS
bspc config normal_border_color           "#504945"
bspc config focused_border_color          "#a89984"
bspc config presel_feedback_color	      "#458588"

# RULES
bspc rule -a Galculator state=floating
bspc rule -a Gksu-properties state=floating
bspc rule -a Brave-browser desktop=WEB
bspc rule -a Pcmanfm desktop=FILES
bspc rule -a discord desktop=CHAT
