#! /bin/sh

# AUTOSTART
sxhkd &
setxkbmap pl
export GDK_SCALE=2
/home/eryk/.config/polybar/launch.sh
#/home/eryk/.fehbg
nitrogen --restore
picom -b &

# MONITORS
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# CONFIGURATION
bspc config border_width                  3
bspc config window_gap                    18
bspc config top_padding		              45
bspc config split_ratio                   0.52
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             false
bspc config focus_follows_pointer         false
bspc config history_aware_focus           false
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# COLORS
bspc config normal_border_color		      "#363636"
bspc config active_border_color	          "#363636"
bspc config focused_border_color	      "#B6A072"
bspc config presel_feedback_color	      "#AD7F26"
bspc config urgent_border_color 	      "#363636"

# RULES
bspc rule -a Galculator state=floating
